### ISSUE TITLE
got lots of error in Slider.qml since 6a4d7fd6204dd0aa8cd06ad405f9af6bb7c55da6

### ISSUE THREAD

**Issue by avilleret** [jcelerier/qml-creative-controls#2]
when running Gallery.qml, I got lots of : 

````
file:///home/antoine/Qt/5.8/gcc_64/qml/CreativeControls/Slider.qml:13:14: Unable to assign QColor to double
file:///home/antoine/Qt/5.8/gcc_64/qml/CreativeControls/Slider.qml:97:18: Unable to assign QColor to double
````

since 6a4d7fd6204dd0aa8cd06ad405f9af6bb7c55da6

**Comment by aklevy** [comment]
try erasing all the *.qmlc files  (whenever a property is added to the singleton Styles.qml, it seems that qmlc files generate this error)

**Comment by avilleret** [comment]
simple enough, thanks !
